#  Consider the below code to answer further questions:t_)

## import numpy as np
## list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
## array_list = np.array(object = list_)


## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to  print the data types of both the variable.s

In [4]:
import numpy as np
list = ["1", "2", "3", "4", "5"]
array_list = np.array(object=list)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
type(array_list)

numpy.ndarray

In [7]:
type(list)

list

### Yes, both the variables are very different form each other, because the data type of the array_list is "NDARRAY" and data type of the given LIST is "STRING".

#

## Q2. Write a code to print the data type of each and every element of both the variables list_ and  array_list.

In [9]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


#

##  Q3. Considering the following changes in the variable, array_list: 
## array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list
a d aryra_list.

In [12]:
array_list = np.array(list, dtype = int)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [15]:
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


#### Yes, still there is a very big difference in the data type of the elements of both the variable_list and array_list. the data type of the elements of the variable list is "STRING" and the data type of the elements of the array_list is "Int"

##

##  Consider the below code to answer further questions

In [18]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) Size
## (ii) Shape

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.ndim

2

In [23]:
num_array.size # total number of elements present in the array

6

In [24]:
num_array.shape # tell about the rows X columns of the array

(2, 3)

## Q.5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array ccreation function 
 [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
##  [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.


In [28]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])